### PR TITLE
Heap Sorting Algorithm In Python

### PR DESCRIPTION
**Pull request by Double77x**
Sorts an array using a Heap Sorting Algorithm in Python.

### CODE REVIEW

**Review by nishitjain1204 — CHANGES_REQUESTED** [review]
Please add proper comments 
Wrap the main code inside a function `main()`

**Comment by Double77x** [comment]
Hi, I have added some comments to the code and standardised some naming to ensure the comments make more sense. What do you mean by wrap the code inside a function main() ? I'm a little lost as to how that is necessary? Could you explain?

**Comment by nishitjain1204** [comment]
> Hi, I have added some comments to the code and standardised some naming to ensure the comments make more sense. What do you mean by wrap the code inside a function main() ? I'm a little lost as to how that is necessary? Could you explain?

[refer this](https://stackoverflow.com/questions/419163/what-does-if-name-main-do)

**Comment by Double77x** [comment]
> > Hi, I have added some comments to the code and standardised some naming to ensure the comments make more sense. What do you mean by wrap the code inside a function main() ? I'm a little lost as to how that is necessary? Could you explain?
> 
> [refer this](https://stackoverflow.com/questions/419163/what-does-if-name-main-do)

Hi, thank you for the link - I understand, I have made the changes. Thank you.

**Review by nishitjain1204 — APPROVED** [review]

**Pull request merged**
